version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Updating apt-get
          command: apt-get update
      - run:
          name: Installing compilers
          command: apt-get install -y g++
      - run:
          name: Installing CMake
          command: apt-get install -y cmake
      - run:
          name: Installing SDL2
          command: apt-get install -y libsdl2-dev
      - run:
          name: Installing SDL_image
          command: apt-get install -y libsdl2-image-dev
      - run:
          name: Installing SDL_ttf
          command: apt-get install -y libsdl2-ttf-dev
      - run:
          name: Generating Makefile
          command: cmake .
      - run:
          name: Building
          command: make