version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Installing CMake
          command: sudo apt-get install cmake
      - run:
          name: Generating Makefile
          command: cmake .
      - run:
          name: Building
          command: make