version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Installing CMake
          command: |
            apt-get update
            apt-get install -y cmake
      - run:
          name: Generating Makefile
          command: cmake .
      - run:
          name: Building
          command: make